### ISSUE TITLE
Plugin is Currently Broken

### ISSUE THREAD

**Issue by jchambo** [haggbart/rustplugin-autoturretauth#1]
@haggbart - Greetings - your plugin is currently broken and does not work. Attempts to reach out on uMod have not been successful.

**Comment by haggbart** [comment]
Thanks @jchambo, fix coming

**Comment by jchambo** [comment]
@haggbart Awesome! Looking forward to the update on uMod! Thanks!

**Comment by haggbart** [comment]
[AutoTurretAuth (2).zip](https://github.com/user-attachments/files/16057774/AutoTurretAuth.2.zip)
Ninja fix @jchambo 

I haven't been able to test it unfortunately.

**Comment by haggbart** [comment]
[AutoTurretAuth (3).zip](https://github.com/user-attachments/files/16057853/AutoTurretAuth.3.zip)
possible improvement

**Comment by jchambo** [comment]
@haggbart - Great! I will test here shortly and report back.

**Comment by jchambo** [comment]
@haggbart - Unfortunately that did not resolve it.

**Comment by haggbart** [comment]
If I find time, I'll test it tomorrow, if not I don't have time until friday. Thanks for trying

**Comment by haggbart** [comment]
https://umod.org/plugins/auto-turret-authorization#updates @jchambo
